"""empty message

Revision ID: 200f74e9569b
Revises: 2e815655138e
Create Date: 2020-02-08 14:36:16.657614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200f74e9569b'
down_revision = '2e815655138e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
